/** The built-in lists from docs/05-risk-model.md. Repository overrides add to them. */

export const SENSITIVE_PATHS: readonly string[] = [
  '**/auth/**',
  '**/authn/**',
  '**/authz/**',
  '**/rbac/**',
  '**/permission*/**',
  '**/session*/**',
  '**/payment*/**',
  '**/billing/**',
  '**/invoice*/**',
  '**/migrations/**',
  '**/migration/**',
  '**/*.sql',
  '**/infra/**',
  '**/terraform/**',
  '**/*.tf',
  '**/helm/**',
  '**/charts/**',
  '**/k8s/**',
  'deploy/**/*.yaml',
  '**/deploy/**/*.yaml',
  'infra/**/*.yaml',
  '**/infra/**/*.yaml',
  '.github/workflows/**',
  'Dockerfile*',
  '**/Makefile',
  '**/crypto/**',
  '**/secret*/**',
  '**/*token*',
  '**/*credential*',
];

export const GENERATED_PATHS: readonly string[] = [
  '**/*.pb.go',
  '**/*.pb.gw.go',
  '**/*_grpc.pb.go',
  '**/*.pb.ts',
  '**/*_pb2.py',
  '**/*_pb2_grpc.py',
  '**/mocks/**',
  '**/mock_*.go',
  '**/*_mock.go',
  '**/*.gen.go',
  '**/*_gen.go',
  '**/*.generated.*',
  '**/zz_generated*',
  '**/gen/**',
  '**/generated/**',
  'package-lock.json',
  'pnpm-lock.yaml',
  'yarn.lock',
  'go.sum',
  'Cargo.lock',
  'poetry.lock',
  'uv.lock',
  '**/*.min.js',
  '**/*.min.css',
  '**/*.snap',
];

export const TEST_PATHS: readonly string[] = [
  '**/*_test.go',
  '**/*.test.ts',
  '**/*.test.tsx',
  '**/*.spec.ts',
  '**/test_*.py',
  '**/*_test.py',
  '**/__tests__/**',
  '**/testdata/**',
];

export const MIGRATION_PATHS: readonly string[] = ['**/migrations/**', '**/*.sql'];

export const HAZARDS: Record<string, readonly string[]> = {
  go: [
    'go func',
    'sync.',
    'atomic.',
    'unsafe.',
    'recover()',
    'context.WithTimeout',
    'time.Sleep',
    'select {',
    'chan ',
    'defer',
    'panic(',
    'os.Exit',
    'exec.Command',
    'sql.',
    'Exec(',
    'Query(',
    'http.Client',
    'tls.',
    'rand.',
  ],
  ts: [
    'eval(',
    'dangerouslySetInnerHTML',
    'innerHTML',
    'child_process',
    'fetch(',
    'localStorage',
    'setTimeout',
    'Promise.race',
    'as any',
    '@ts-ignore',
  ],
};

export const ERROR_PATH_PATTERNS: readonly string[] = [
  'err != nil',
  'return nil, ',
  'catch',
  'throw',
  'panic(',
];

export const BUGFIX_SUBJECT = /\b(fix|fixes|fixed|bug|hotfix|revert|regression)\b/i;
