import { describe, expect, it } from 'vitest';
import { detectGenerated, generatedRule, HEADER_RULE } from '../src/generated.js';
import { firstMatch, matchesGlob } from '../src/glob.js';
import { SENSITIVE_PATHS, TEST_PATHS } from '../src/patterns.js';

describe('glob matching', () => {
  it('spans path segments with ** and stays inside one with *', () => {
    expect(matchesGlob('api/gen/tenant/service.pb.go', '**/*.pb.go')).toBe(true);
    expect(matchesGlob('service.pb.go', '**/*.pb.go')).toBe(true);
    expect(matchesGlob('api/gen/service.pbgo', '**/*.pb.go')).toBe(false);
    expect(matchesGlob('api/v1/auth/token.go', '**/auth/**')).toBe(true);
    expect(matchesGlob('api/v1/authorization/token.go', '**/auth/**')).toBe(false);
  });

  it('matches a pattern without a slash against the basename', () => {
    expect(matchesGlob('web/package-lock.json', 'package-lock.json')).toBe(true);
    expect(matchesGlob('build/Dockerfile.ci', 'Dockerfile*')).toBe(true);
    expect(matchesGlob('build/notadockerfile', 'Dockerfile*')).toBe(false);
  });

  it('reports the first pattern that matched', () => {
    expect(firstMatch('db/migrations/0042_add.sql', SENSITIVE_PATHS)).toBe('**/migrations/**');
    expect(firstMatch('pkg/tenant/service.go', SENSITIVE_PATHS)).toBeNull();
    expect(firstMatch('.github/workflows/ci.yaml', SENSITIVE_PATHS)).toBe('.github/workflows/**');
    expect(firstMatch('deploy/base/values.yaml', SENSITIVE_PATHS)).toBe('deploy/**/*.yaml');
  });

  it('knows the test naming conventions', () => {
    for (const path of [
      'pkg/tenant/service_test.go',
      'web/src/app.test.ts',
      'web/src/app.test.tsx',
      'web/src/app.spec.ts',
      'py/test_service.py',
      'py/service_test.py',
      'web/src/__tests__/app.ts',
      'pkg/tenant/testdata/case.json',
    ]) {
      expect(firstMatch(path, TEST_PATHS), path).not.toBeNull();
    }
    expect(firstMatch('pkg/tenant/service.go', TEST_PATHS)).toBeNull();
  });
});

describe('generated detection', () => {
  it('names the built-in pattern that matched', () => {
    expect(generatedRule('api/gen/tenant/service.pb.go', [])).toBe('**/*.pb.go');
    expect(generatedRule('pkg/mocks/store.go', [])).toBe('**/mocks/**');
    expect(generatedRule('go.sum', [])).toBe('go.sum');
    expect(generatedRule('web/src/__snapshots__/app.snap', [])).toBe('**/*.snap');
    expect(generatedRule('pkg/tenant/zz_generated_deepcopy.go', [])).toBe('**/zz_generated*');
  });

  it('reads the Go header convention within the first five lines', () => {
    const header = ['// Code generated by protoc-gen-go. DO NOT EDIT.', '', 'package tenant'];
    expect(generatedRule('pkg/tenant/wire.go', header)).toBe(HEADER_RULE);
    expect(generatedRule('pkg/tenant/wire.go', ['package tenant'])).toBeNull();
  });

  it('ignores the header when it arrives after the fifth line', () => {
    const late = ['1', '2', '3', '4', '5', '// Code generated by x. DO NOT EDIT.'];
    expect(generatedRule('pkg/tenant/wire.go', late)).toBeNull();
  });

  it('takes repository patterns before the built-in ones', () => {
    expect(generatedRule('api/schema/types.ts', ['export type A = 1;'], ['api/schema/**'])).toBe(
      'api/schema/**',
    );
  });

  it('keeps the rule and stops folding when folding is off', () => {
    expect(detectGenerated('api/gen/x.pb.go', [], [], true)).toEqual({
      is: true,
      rule: '**/*.pb.go',
    });
    expect(detectGenerated('api/gen/x.pb.go', [], [], false)).toEqual({
      is: false,
      rule: '**/*.pb.go',
    });
  });

  it('leaves a hand-written file alone', () => {
    expect(detectGenerated('pkg/tenant/service.go', ['package tenant'])).toEqual({
      is: false,
      rule: null,
    });
  });
});
